### ISSUE TITLE
 Undefined index: background_image

### ISSUE THREAD

**Issue by gfuentesmorales** [ractoon/acf-section-styles#3]
Hi your plugin have error in

Error in Notice: Undefined index: background_image in /home/web/vallenevado/sitio/wp-content/plugins/acf-section-styles-master/fields/acf-section_styles-v5.php on line 451

Your add isset in line  451

```
if ( isset($field['value']['background_image'] )) {
        // update vars
	$url = wp_get_attachment_image_src($field['value']['background_image'], 'medium');
         // url exists
	if ( $url ) {
	  $url = $url[0];
	  $div['class'] .= ' has-value';
	}
}
```

**Comment by ractoon** [comment]
Hi @gfuentesmorales, thanks for the heads up. This should now be fixed in version 1.2.2.
